server:
  port: 31001
spring:
  application:
    name: yy-service-manage-cms
  data:
    mongodb:
      uri:  mongodb://localhost:27017/yy_cms
      database: yy_cms
freemarker:
    cache: false  #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0 #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试